{
 "title": "Bank App Statistics",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Blocked Cash Operations by Login & Currency",
   "type": "table",
   "description": "Количество блокировок операций с наличными",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(operation_cash_blocked_total) by (login, currency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Transfer Operations by Logins & Currency",
   "type": "table",
   "description": "Количество блокировок операций с наличными",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(operation_transfer_blocked_total) by (fromCurrency, fromLogin, toCurrency, toLogin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество успешных входов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(custom_login_total{status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Топ 10 пользователей с неуспешным входом",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (custom_login_total{status=\"failure\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Notifications by Email",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(email) (notification_failed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Задержка обновления курсов валют, секунд",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "currency_rate_delay_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество неуспешных входов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(custom_login_total{status=\"failure\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}