pipeline {
    agent any

    environment {
        RELEASE_NAME    = 'zipkin'
        NAMESPACE       = 'monitoring'
    }

    stages {
        stage('Deploy Zipkin') {
            steps {
                dir('zipkin') {
                    sh '''
                    echo "Deploy Zipkin in cluster..."
                    if ! kubectl get namespace | grep $NAMESPACE; then
                        kubectl create namespace $NAMESPACE
                    fi

                    if ! helm list -n $NAMESPACE | grep $RELEASE_NAME; then
                        helm upgrade --install $RELEASE_NAME ./zipkin -n $NAMESPACE --wait
                    fi
                    '''
                }
            }
        }
    }
    post {
        failure {
            echo 'Произошел сбой конвейера. Изучите журналы, приведенные выше.'
        }
        success {
            echo 'Кластер Zipkin был развернут и тесты прошли успешно.'
        }
    }
}

