apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications-service.fullname" . }}
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}

  SERVER_PORT: {{ .Values.service.port }}
  SERVICE_DB_HOST: {{ .Release.Name }}{{ .Chart.Name }}-db
  SPRING_APPLICATION_NAME: {{ include "notifications-service.fullname" . }}