apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topics
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      name: kafka-create-topics
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-client
          image: docker.io/bitnami/kafka:4.0.0-debian-12-r7
          command:
            - /bin/bash
            - -c
            - |
              echo "Creating Kafka topics..."
              {{- range .Values.kafka.topics }}
              kafka-topics.sh --bootstrap-server kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092 \
              --create --if-not-exists \
              --replication-factor {{ .replicationFactor }} \
              --partitions {{ .partitions }} \
              --topic {{ .name }}{{- if .minInsyncReplicas }} \
              --config min.insync.replicas={{ .minInsyncReplicas }}
              {{- end }}
              {{- end }}
              echo "Done."