services:
  spring-cloud-config-server:
    build:
      context: ./config-server
    image: config_server:1.0.0
    container_name: ${CONFIG_SERVER_HOST:-spring-cloud-config-server}
    hostname: ${CONFIG_SERVER_HOST:-spring-cloud-config-server}
    environment:
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT:-8888}
    expose:
      - "${CONFIG_SERVER_PORT:-8888}"
    ports:
      - "${CONFIG_SERVER_PORT:-8888}:${CONFIG_SERVER_PORT:-8888}"
    healthcheck:
      test: "curl --fail --silent localhost:${CONFIG_SERVER_PORT:-8888}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  eureka-server:
    build:
      context: ./eureka-server
    image: eureka-server:1.0.0
    container_name: eureka-server
    hostname: eureka-server
    environment:
      CONFIG_SERVER_HOST: ${CONFIG_SERVER_HOST:-spring-cloud-config-server}
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT:-8888}
    expose:
      - "8761"
    ports:
      - "8761:8761"
    depends_on:
      spring-cloud-config-server:
        condition: service_healthy