apiVersion: v2
name: notifications-service
description: Helm chart for the notifications-service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Dependency for Notifications DB (PostgreSQL)
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.x.x