apiVersion: v2
name: notifications-service
description: Helm chart for the notifications-service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Dependency for Notifications DB (PostgreSQL)
  - name: postgresql
    version: "16.7.10"
    repository: "file://../postgresql"
    alias: notifications-db
    condition: notifications-db.enabled