apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-ui.fullname" . }}-config
data:
  application.yml: |
    server:
      forward-headers-strategy: framework
      servlet:
        context-path: /

      reactive:
        session:
          cookie:
            name: SESSION_${spring.application.name}

    logging:
      level:
        org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus,refresh
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
      zipkin:
        tracing:
          endpoint: ${ZIPKIN_URL}/api/v2/spans
        sampling:
          probability: 1
    spring:
      thymeleaf:
        check-template-location: true
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        cache: false
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: ${KEYCLOAK_ISSUER_URL} # Адрес сервера авторизации для получения токена
            {{- if and .Values.config .Values.config.oauth2 }}
            registration:
              {{- range .Values.config.oauth2 }}
              {{ .client_id }}:
                provider: keycloak
                client-id: {{ .client_id }}
                client-secret: {{ printf "${%s}" .secret_name }}
                scope: {{ .scope }}
                authorization-grant-type: client_credentials
                clientAuthenticationMethod: client_secret_post
              {{- end }}
            {{- end }}
      rest:
        cash-service:
          url: ${GATEWAY_API_URL}/cash-service
        transfer-service:
          url: ${GATEWAY_API_URL}/transfer-service
        accounts-service:
          url: ${GATEWAY_API_URL}/accounts-service