apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: front-ui-route
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - name: {{ $.Values.gateway.gatewayName }}
      namespace: {{ $.Values.gateway.gatewayNamespace }}
  hostnames:
    - "bankapp.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "front-ui.fullname" $ }}
          port: {{ $.Values.service.port }}