apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: front-ui-route
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - name: {{ $.Values.gateway.gatewayName }}
      namespace: {{ $.Values.gateway.gatewayNamespace }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /
        - path:
            type: Exact
            value: /main
        - path:
            type: PathPrefix
            value: /login
        - path:
            type: PathPrefix
            value: /logout
        - path:
            type: Exact
            value: /signup
        - path:
            type: PathPrefix
            value: /actuator
        - path:
            type: PathPrefix
            value: /css
        - path:
            type: PathPrefix
            value: /user
      backendRefs:
        - name: {{ include "front-ui.fullname" $ }}
          port: {{ $.Values.service.port }}