apiVersion: v2
name: elastic
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: elasticsearch
    version: 22.0.8
    repository: oci://registry-1.docker.io/bitnamicharts