openapi: 3.0.3
info:
  title: Blocker Service API
  description: RESTful API для сервиса блокировки подозрительных операций
  version: 1.0.0

paths:
  /api/v1/check_transaction:
    post:
      summary: Проверка денежной операции
      description: Производит проверку денежной операции и возвращает флаг блокировки
      operationId: checkTransaction
      tags:
        - Blocker Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/CashTransactionRequest'
                - $ref: '#/components/schemas/TransferTransactionRequest'
              discriminator:
                propertyName: operationType
                mapping:
                  cash: CashTransactionRequest
                  transfer: TransferTransactionRequest
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTransactionResponse'
        '400':
          description: Ошибочный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CashTransactionRequest:
      type: object
      required: [ transactionId, currencyCode, source, target, amount, operationType ]
      properties:
        transactionId:
          type: integer
          format: int64
          description: Идентификатор транзакции
          example: 10546379
        currencyCode:
          $ref: '#/components/schemas/CurrencyEnum'
        source:
          $ref: '#/components/schemas/CorrespondentEnum'
        target:
          $ref: '#/components/schemas/CorrespondentEnum'
        amount:
          type: number
          format: double
          minimum: 0.0000001
        operationType:
          type: string
          description: Тип операции
          pattern: ^(cash|transfer)$
          example: cash

    TransferTransactionRequest:
      type: object
      required: [ transactionId, from, to, amount, operationType, isToYourself ]
      properties:
        transactionId:
          type: integer
          format: int64
          description: Идентификатор транзакции
          example: 10546379
        from:
          type: object
          required: [ currencyCode, source ]
          properties:
            currencyCode:
              $ref: '#/components/schemas/CurrencyEnum'
            source:
              $ref: '#/components/schemas/CorrespondentEnum'
        to:
          type: object
          required: [ currencyCode, target ]
          properties:
            currencyCode:
              $ref: '#/components/schemas/CurrencyEnum'
            target:
              $ref: '#/components/schemas/CorrespondentEnum'
        amount:
          type: number
          format: double
          minimum: 0.0000001
        operationType:
          type: string
          description: Тип операции
          pattern: ^(cash|transfer)$
          example: cash
        isToYourself:
          type: boolean
          description: Флаг перевода самому себе
          example: false


    CheckTransactionResponse:
      type: object
      required:
        - isBlocked
        - transactionId
      properties:
        transactionId:
          type: integer
          format: int64
          description: Идентификатор транзакции
        isBlocked:
          type: boolean
          description: Флаг блокировки транзакции
          example: false
        reason:
          type: string
          description: Причина блокировки
          example: Сумма перевода больше 600000 руб.

    ErrorResponse:
      type: object
      required:
        - message
        - status_code
      properties:
        message:
          type: string
          example: Внутренняя ошибка сервера
        status_code:
          type: integer
          description: Код ошибки
          example: 500
    CorrespondentEnum:
      type: string
      description: Тип получателя. cash - внесение наличных денежных средств, account - пополнение счета
      enum:
        - account
        - cash
      example: account

    CurrencyEnum:
      type: string
      enum:
        - USD
        - RUB
        - CNY