openapi: 3.0.3
info:
  title: Blocker Service API
  description: RESTful API для сервиса блокировки подозрительных операций
  version: 1.0.0

paths:
  /api/v1/blocker/checkCashTransaction:
    post:
      summary: Проверка денежной операции с наличными
      description: Производит проверку денежной операции с наличными и возвращает флаг блокировки
      operationId: checkCashTransaction
      tags:
        - Blocker Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckCashTransactionRequest'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTransactionResponse'
        '400':
          description: Ошибочный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockerErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockerErrorResponse'
  /api/v1/blocker/checkTransferTransaction:
    post:
      summary: Проверка денежной операции перевода между счетами
      description: Производит проверку денежной операции перевода между счетами и возвращает флаг блокировки
      operationId: checkTransferTransaction
      tags:
        - Blocker Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckTransferTransactionRequest'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTransactionResponse'
        '400':
          description: Ошибочный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockerErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockerErrorResponse'

components:
  schemas:
    CheckCashTransactionRequest:
      type: object
      required: [ transactionId, currency, amount, actionType ]
      properties:
        transactionId:
          type: integer
          format: int64
          description: Идентификатор транзакции
          example: 10546379
        currency:
          $ref: '#/components/schemas/BlockerCurrencyEnum'
        amount:
          type: number
          format: double
          minimum: 0.0000001
        actionType:
          type: string
          description: Тип операции
          enum:
            - PUT  # внесение ДС
            - GET  # снятие ДС
          example: GET

    CheckTransferTransactionRequest:
      type: object
      required: [ transactionId, fromCurrency, toCurrency, amount, isItself ]
      properties:
        transactionId:
          type: integer
          format: int64
          description: Идентификатор транзакции
          example: 10546379
        fromCurrency:
          $ref: '#/components/schemas/BlockerCurrencyEnum'
        toCurrency:
          $ref: '#/components/schemas/BlockerCurrencyEnum'
        amount:
          type: number
          format: double
          minimum: 0.0000001
        isItself:
          type: boolean
          description: Флаг перевода самому себе
          example: false

    CheckTransactionResponse:
      type: object
      required:
        - isBlocked
        - transactionId
      properties:
        transactionId:
          type: integer
          format: int64
          description: Идентификатор транзакции
        isBlocked:
          type: boolean
          description: Флаг блокировки транзакции
          example: false
        reason:
          type: string
          description: Причина блокировки
          example: Сумма перевода больше 600000 руб.

    BlockerErrorResponse:
      type: object
      required:
        - message
        - status_code
      properties:
        message:
          type: string
          example: Внутренняя ошибка сервера
        status_code:
          type: integer
          description: Код ошибки
          example: 500
    CorrespondentEnum:
      type: string
      description: Тип получателя. cash - внесение наличных денежных средств, account - пополнение счета
      enum:
        - account
        - cash
      example: account

    BlockerCurrencyEnum:
      type: string
      enum:
        - USD
        - RUB
        - CNY