openapi: 3.0.3
info:
  title: Exchange Service API
  description: RESTful API для сервиса конвертации валют
  version: 1.0.0

paths:
  /api/v1/convert:
    post:
      summary: Конвертация валюты по текущему курсу
      description: Производит расчет суммы конвертации
      operationId: convertCurrency
      tags:
        - Exchange Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertRequest'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConvertedAmount'
        '400':
          description: Ошибочный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/rates:
    post:
      summary: Регистрация новых курсов конвертации
      description: Производит сохранение новых курсов конвертации, полученных от Exchange Generator
      operationId: createRates
      tags:
        - Exchange Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeRateRequest'
      responses:
        '201':
          description: Успешно
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Ошибочный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Получение курсов конвертации валют
      description: Возвращает значение текущего курса конвертации валют
      operationId: getRates
      tags:
        - Exchange Service
      responses:
        '200':
          description: Успешный ответ с курсами конвертации валют
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRatesResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ConvertRequest:
      type: object
      required:
        - from
        - to
        - amount
      properties:
        from:
          type: string
          description: Код исходной валюты
          example: USD
          minLength: 3
          maxLength: 3
        to:
          type: string
          description: Код валюты конвертации
          example: RUB
          minLength: 3
          maxLength: 3
        amount:
          type: number
          format: double
          description: Сумма для конвертации
          example: 1000.50
          minimum: 0.0000001

    ConvertedAmount:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: double
          example: 1058,8

    ExchangeRateRequest:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp в секундах, когда были сгенерированы курсы
        rates:
          type: array
          items:
            $ref: '#/components/schemas/Rate'
      required:
        - timestamp
        - rates

    Rate:
      type: object
      properties:
        title:
          type: string
          example: "Доллар"
          description: Название валюты на русском языке
        name:
          type: string
          example: "USD"
          description: Код валюты (например, USD, CNY, RUB)
        value:
          type: number
          format: double
          example: 0.013
          description: Курс валюты по отношению к рублю
      required:
        - title
        - name
        - value

    ExchangeRatesResponse:
      type: array
      items:
        $ref: '#/components/schemas/Rate'

    ErrorResponse:
      type: object
      required:
        - message
        - status_code
      properties:
        message:
          type: string
          example: Внутренняя ошибка сервера
        status_code:
          type: integer
          example: 500