openapi: 3.0.3
info:
  title: Transfer Service API
  description: RESTful API для сервиса перевода денег между счетами
  version: 1.0.0

paths:
  /api/v1/transfer:
    post:
      summary: Операция перевода денег между счетами (своими или на счет другого пользователя)
      description: Осуществляет перевод денег между счетами
      operationId: transferTransaction
      tags:
        - Transfer Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferOperationRequest'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferOperationResponse'
        '400':
          description: Ошибочный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferErrorListResponse'
        '403':
          description: Операция заблокирована
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferErrorResponse'
        '404':
          description: Пользователь с указанным login не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferErrorResponse'
        '422':
          description: Ошибки в процессе обработки перевода
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferOperationResponse'
        '503':
          description: Сервис или связанные сервисы временно не доступны
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferErrorResponse'

components:
  schemas:
    TransferOperationRequest:
      type: object
      required:
        - fromLogin
        - fromCurrency
        - toLogin
        - toCurrency
        - amount
      properties:
        fromLogin:
          type: string
          pattern: '^[A-Za-z\d_-]+$'
          description: Логин пользователя осуществляющего перевод
        fromCurrency:
          $ref: '#/components/schemas/TransferCurrencyEnum'
        toLogin:
          type: string
          pattern: '^[A-Za-z\d_-]+$'
          description: Логин пользователя для перевода. При переводе самому себе совпадает с login
        toCurrency:
          $ref: '#/components/schemas/TransferCurrencyEnum'
        amount:
          type: number
          format: double
          description: Сумма перевода в валюте счета отправителя

    TransferErrorResponse:
      type: object
      required:
        - message
        - status_code
      properties:
        message:
          type: string
          example: Внутренняя ошибка сервера
        status_code:
          type: integer
          example: 500

    TransferErrorListResponse:
      type: object
      required:
        - message
        - status_code
      properties:
        messages:
          type: array
          items:
            type: string
        status_code:
          type: integer
          example: 500

    TransferOperationResponse:
      type: object
      required:
        - operationStatus
        - errors
      properties:
        operationStatus:
          type: string
          enum:
            - SUCCESS
            - FAILED
        errors:
          type: array
          items:
            type: string

    TransferCurrencyEnum:
      type: string
      enum:
        - CNY
        - RUB
        - USD
