apiVersion: v2
name: accounts-service
description: Helm chart for the accounts-service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Dependency for Accounts DB (PostgreSQL)
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.x.x