apiVersion: v2
name: accounts-service
description: Helm chart for the accounts-service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Dependency for Accounts DB (PostgreSQL)
  - name: postgresql
    version: "16.7.10"
    repository: "file://../postgresql"
    alias: accounts-db
    condition: accounts-db.enabled