logstash:
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 10
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 10
  persistence:
    enabled: true

  input: |-
    kafka {
        bootstrap_servers => "bank-app-kafka-bootstrap.kafka.svc.cluster.local:9092"
        topics => ["logs"]
        group_id => "logstash-log-consumer"
        codec => "json"
      }
  filter: |-
    filter {
      if [@timestamp] {
        date {
          match => ["@timestamp", "ISO8601"]
        }
      }
  
      mutate {
        lowercase => ["level"]
      }
  
      if [mdc] {
        ruby {
          code => '
            mdc = event.get("mdc")
            if mdc.is_a?(Hash)
              mdc.each { |k, v| event.set("mdc_#{k}", v) }
            end
          '
        }
        remove_field => ["mdc"]
      }
    }
  output: |-
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "logs-%{+YYYY.MM.dd}"
      retry_on_conflict => 3
      action => "index"
      workers => 4
    }
  resources:
    limits:
      cpu: 500m       # максимум пол-ядра
      memory: 1Gi     # максимум 1 гигабайт RAM
    requests:
      cpu: 250m       # гарантированно четверть ядра
      memory: 512Mi   # гарантированно 512 Мб RAM