apiVersion: v2
name: transfer-service
description: Helm chart for the transfer-service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Dependency for Transfer DB (PostgreSQL)
  - name: postgresql
    version: "16.7.10"
    repository: "file://../postgresql"
    alias: transferDatabase
    condition: transferDatabase.enabled