apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-delay-get-currency-rate-alert
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
    - name: currency.rate.delay
      rules:
        - alert: HighDelayGetNewCurrencyRate
          expr: currency_rate_delay_seconds > 30 # Курсы валют не обновлялись более 30 сек
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Нет обновления курсов валют"
            description: "Курсы валют не обновлялись более 30 сек."
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: user-login-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
    - name: user.login.alerts
      rules:
        - alert: TooManyFailedLogins
          expr: increase(user_login_attempts{outcome="failure"}[1m]) > 10
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Много неуспешных логинов за последнюю минуту"
            description: "Более 10 неуспешных попыток входа за последнюю минуту."