apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-delay-get-currency-rate-alert
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
    - name: currency.rate.delay
      rules:
        - alert: HighDelayGetNewCurrencyRate
          expr: currency_rate_delay_seconds > 30 # Курсы валют не обновлялись более 30 сек
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Нет обновления курсов валют"
            description: "Курсы валют не обновлялись более 30 сек."
