apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker-service.fullname" . }}
  labels:
    {{- include "blocker-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
    {{- if ne $key "oauth2" }}
    {{ $key | upper }}: {{ $value | quote }}
    {{- end }}
    {{- end }}

    SERVER_PORT: {{ .Values.service.port | quote }}
    SPRING_APPLICATION_NAME: {{ include "blocker-service.fullname" . }}