apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker-service.fullname" . }}-config
data:
  application.yml: |
    openapi:
      service:
        base-path: /
    springdoc:
      swagger-ui:
        enabled: true
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus,refresh
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
      zipkin:
        tracing:
          endpoint: ${ZIPKIN_URL}/api/v2/spans
        sampling:
          probability: 1
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: ${KEYCLOAK_ISSUER_URL}