apiVersion: v1
kind: Service
metadata:
  name: {{ include "cash-service.fullname" . }}
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
    app: {{ include "cash-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http # Match the container port *name* in the deployment
      protocol: TCP
      name: http
  selector:
    {{- include "cash-service.selectorLabels" . | nindent 4 }}