apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
    {{- if ne $key "oauth2" }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  SERVER_PORT: {{ .Values.service.port | quote }}
  SPRING_APPLICATION_NAME: {{ include "transfer-service.fullname" . }}
  SPRING_REST_NOTIFICATIONS_SERVICE_URL: {{ printf "http://notifications-service.%s.local" .Release.Namespace }}
  SPRING_REST_ACCOUNTS_SERVICE_URL: {{ printf "http://accounts-service.%s.local" .Release.Namespace }}
  SPRING_REST_BLOCKER_SERVICE_URL: {{ printf "http://blocker-service.%s.local" .Release.Namespace }}
  SPRING_REST_EXCHANGE_SERVICE_URL: {{ printf "http://exchange-service.%s.local" .Release.Namespace }}
  SERVICE_DB_HOST: {{ .Release.Name }}-transfer-db.{{ .Release.Namespace }}.svc.cluster.local