spring:
  application:
    name: cash-service

  cloud:
    config:
      enabled: false

  security:
    enabled: false

  rabbitmq:
    listener:
      direct:
        auto-startup: false

  rest:
    notifications-service:
      url: http://localhost:7081
    blocker-service:
      url: http://localhost:7082
    accounts-service:
      url: http://localhost:7083

eureka:
  client:
    enabled: false

openapi:
  accountsService:
    base-path: /


