apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-generator.fullname" . }}
  labels:
    {{- include "exchange-generator.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
    {{- if ne $key "oauth2" }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  SERVER_PORT: {{ .Values.service.port | quote }}
  SPRING_APPLICATION_NAME: {{ include "exchange-generator.fullname" . }}