apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-generator.fullname" . }}-config
data:
  application.yml: |
    openapi:
      service:
        base-path: /
    springdoc:
      swagger-ui:
        enabled: true
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus,refresh
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
    spring:
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: ${KEYCLOAK_ISSUER_URL} # Адрес сервера авторизации для получения токена
            {{- if and .Values.config .Values.config.oauth2 }}
            registration:
              {{- range .Values.config.oauth2 }}
              {{ .client_id }}:
              provider: keycloak
              client-id: {{ .client_id }}
              client-secret: {{ printf "${%s}" .secret_name }}
              scope: {{ .scope }}
              authorization-grant-type: client_credentials
              clientAuthenticationMethod: client_secret_post
              {{- end }}
            {{- end }}