pipeline {
    agent any

    environment {
        DOCKER_REGISTRY                     = credentials('DOCKER_REGISTRY')
        ACCOUNTS_SERVICE_DB_PASSWORD        = credentials('ACCOUNTS_SERVICE_DB_PASSWORD')
        CASH_SERVICE_DB_PASSWORD            = credentials('CASH_SERVICE_DB_PASSWORD')
        TRANSFER_SERVICE_DB_PASSWORD        = credentials('TRANSFER_SERVICE_DB_PASSWORD')
        EXCHANGE_SERVICE_DB_PASSWORD        = credentials('EXCHANGE_SERVICE_DB_PASSWORD')
        NOTIFICATIONS_SERVICE_DB_PASSWORD   = credentials('NOTIFICATIONS_SERVICE_DB_PASSWORD')
        RABBITMQ_DEFAULT_PASS               = credentials('RABBITMQ_DEFAULT_PASS')
        ACCOUNTS_CLIENT_SECRET              = credentials('ACCOUNTS_CLIENT_SECRET')
        CASH_CLIENT_SECRET                  = credentials('CASH_CLIENT_SECRET')
        EXCHANGE_CLIENT_SECRET              = credentials('EXCHANGE_CLIENT_SECRET')
        NOTIFICATION_CLIENT_SECRET          = credentials('NOTIFICATION_CLIENT_SECRET')
        TRANSFER_CLIENT_SECRET              = credentials('TRANSFER_CLIENT_SECRET')
        BLOCKER_CLIENT_SECRET               = credentials('BLOCKER_CLIENT_SECRET')
        NEXUS_REPOSITORY_RELEASES_URL       = 'http://nexus:8081/repository/maven-releases/'

        GITHUB_USERNAME         = credentials('GITHUB_USERNAME')

        DB_NAME                 = 'app_db'
        ACCOUNTS_DB_USER        = 'accounts_user'
        CASH_DB_USER            = 'cash_user'
        TRANSFER_DB_USER        = 'transfer_user'
        EXCHANGE_DB_USER        = 'exchange_user'
        NOTIFICATIONS_DB_USER   = 'notifications_user'
        IMAGE_TAG               = "${env.BUILD_NUMBER}"

        NEXUS_PASSWORD          = credentials('NEXUS_JENKINS_PASSWORD')
        NEXUS_USER              = 'jenkins'

        STUBRUNNER_PASSWORD     = credentials('NEXUS_JENKINS_PASSWORD')
        STUBRUNNER_USERNAME     = 'jenkins'
    }

    stages {
        stage("Checkout and setup") {
            steps {
                sh 'chmod +x ./gradlew'
            }
        }
        stage("Build And Test Services Without Consumer Contracts") {
            parallel {
                stage('Build And Test Exchange Service') {
                    steps {
                        sh './gradlew :exchange-service:clean :exchange-service:build -PnexusUsername=jenkins -PnexusPassword=$NEXUS_PASSWORD'
                    }
                }
                stage('Build And Test Notifications Service') {
                    steps {
                        sh './gradlew :notifications-service:clean :notifications-service:build -PnexusUsername=jenkins -PnexusPassword=$NEXUS_PASSWORD'
                    }
                }
                stage('Build And Test Blocker Service') {
                    steps {
                        sh './gradlew :blocker-service:clean :blocker-service:build -PnexusUsername=jenkins -PnexusPassword=$NEXUS_PASSWORD'
                    }
                }
            }
        }
        stage("Build And Test Exchange Generator And Accounts Service") {
            parallel {
                stage('Build And Test Exchange Generator') {
                    steps {
                        sh './gradlew :exchange-generator:clean :exchange-generator:build -PnexusUsername=jenkins -PnexusPassword=$NEXUS_PASSWORD'
                    }
                }
                stage('Build And Test Accounts Service') {
                    steps {
                        sh './gradlew :accounts-service:clean :accounts-service:build -PnexusUsername=jenkins -PnexusPassword=$NEXUS_PASSWORD'
                    }
                }
            }
        }
        stage("Build And Test Cash And Transfer Services") {
            parallel {
                stage('Build And Test Cash Service') {
                    steps {
                        sh './gradlew :cash-service:clean :cash-service:build -PnexusUsername=jenkins -PnexusPassword=$NEXUS_PASSWORD'
                    }
                }
                stage('Build And Test Transfer Service') {
                    steps {
                        sh './gradlew :transfer-service:clean :transfer-service:build -PnexusUsername=jenkins -PnexusPassword=$NEXUS_PASSWORD'
                    }
                }
            }
        }
        stage('Build And Test Front UI') {
            steps {
                sh './gradlew :front-ui:clean :front-ui:build -PnexusUsername=jenkins -PnexusPassword=$NEXUS_PASSWORD'
            }
        }
    }
}
