spring:
  application:
    name: transfer-service

  security:
    enabled: false

  rest:
    notifications-service:
      url: http://localhost:7091
    blocker-service:
      url: http://localhost:7092
    accounts-service:
      url: http://localhost:7093
    exchange-service:
      url: http://localhost:7094

openapi:
  transferService:
    base-path: /


