apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  {{- range $key, $value := .Values.global }}
    {{- if ne $key "domain" }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  RABBITMQ_HOST: rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | quote }}

  KEYCLOAK_ISSUER_URL: {{- printf "http://keycloak.%s.svc.cluster.local/realm/bank-app" .Release.Namespace }}