apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  {{- range $key, $value := .Values.global }}
    {{- if ne $key "domain" }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  KEYCLOAK_ISSUER_URL: {{ printf "http://keycloak.%s.svc.cluster.local/realms/bank-app" .Release.Namespace }}
  GATEWAY_API_URL: "http://gateway-nginx.nginx-gateway.svc.cluster.local"
  ZIPKIN_URL: {{ printf "http://zipkin.monitoring-%s.svc.cluster.local:9411" .Release.Namespace }}