apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: gateway
      namespace: nginx-gateway
  hostnames:
    - "keycloak.bankapp.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: keycloak
          port: 80