apiVersion: v2
name: exchange-service
description: Helm chart for the exchange-service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Dependency for Exchange DB (PostgreSQL)
  - name: postgresql
    version: "16.7.10"
    repository: "file://../postgresql"
    alias: exchangeDatabase
    condition: exchangeDatabase.enabled