management:
  endpoints:
    web:
      exposure:
        include: health,refresh,busrefresh,busshutdown

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    healthcheck:
      enabled: true

spring:
  application:
    name: exchange-generator

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

  rest:
    exchange-service:
      url: ${API_GATEWAY_URL}/exchange-service
