openapi:
  exchangeService:
    base-path: /

springdoc:
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,busrefresh,busshutdown

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    healthcheck:
      enabled: true

spring:
  application:
    name: exchange-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}

  r2dbc:
    url: r2dbc:postgresql://${SERVICE_DB_HOST}:5432/app_db
    username: ${SERVICE_DB_USER}
    password: ${SERVICE_DB_PASSWORD}
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения

  liquibase:
    enabled: true
    url: jdbc:postgresql://${SERVICE_DB_HOST}:5432/app_db
    user: ${SERVICE_DB_USER}
    password: ${SERVICE_DB_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: prod

  sql:
    init:
      mode: never

application:
  notification:
    limit: 10