spring:
  application:
    name: exchange-service

  cloud:
    config:
      enabled: false

  security:
    enabled: false

eureka:
  client:
    enabled: false

openapi:
  exchangeService:
    base-path: /
