apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts-service.fullname" . }}
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
    {{- if ne $key "oauth2" }}
    {{ $key | upper }}: {{ $value | quote }}
    {{- end }}
    {{- end }}

    SERVER_PORT: {{ .Values.service.port | quote }}
    SPRING_APPLICATION_NAME: {{ include "accounts-service.fullname" . }}
    SPRING_REST_NOTIFICATIONS_SERVICE_URL: "http://notifications-service.bankapp.local"
    SERVICE_DB_HOST: {{ .Release.Name }}-accounts-db.{{ .Release.Namespace }}.svc.cluster.local