apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.routes.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - name: {{ $.Values.gateway.gatewayName }}
      namespace: {{ $.Values.gateway.gatewayNamespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.routes.path }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ .Values.gateway.routes.service }}
          port: {{ .Values.gateway.routes.port }}
