apiVersion: v2
name: cash-service
description: Helm chart for the cash-service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Dependency for Cash DB (PostgreSQL)
  - name: postgresql
    version: "16.7.10"
    repository: "file://../postgresql"
    alias: cashDatabase
    condition: cashDatabase.enabled
