prometheus:
  server:
    global:
      scrape_interval: 30s      # Интервал сбора метрик
      evaluation_interval: 30s  # Интервал оценки правил
      scrape_timeout: 10s       # Тайм-аут сбора метрик
    # Конфигурация сбора метрик
    scrape_configs:
      # Базовый мониторинг самого Prometheus
      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'http://localhost:9090' ]

      # Сбор метрик микросервисов
      - job_name: 'accounts-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'http://gateway-nginx.nginx-gateway.svc.cluster.local/accounts-service' ]
            labels:
              app: 'accounts-service'
      - job_name: 'cash-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'http://gateway-nginx.nginx-gateway.svc.cluster.local/cash-service' ]
            labels:
              app: 'cash-service'
      - job_name: 'transfer-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'http://gateway-nginx.nginx-gateway.svc.cluster.local/transfer-service' ]
            labels:
              app: 'transfer-service'
      - job_name: 'exchange-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'http://gateway-nginx.nginx-gateway.svc.cluster.local/exchange-service' ]
            labels:
              app: 'exchange-service'
      - job_name: 'exchange-generator'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'http://gateway-nginx.nginx-gateway.svc.cluster.local/exchange-generator' ]
            labels:
              app: 'exchange-generator'
      - job_name: 'notifications-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'http://gateway-nginx.nginx-gateway.svc.cluster.local/notifications-service' ]
            labels:
              app: 'notifications-service'
      - job_name: 'blocker-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'http://gateway-nginx.nginx-gateway.svc.cluster.local/blocker-service' ]
            labels:
              app: 'blocker-service'
      - job_name: 'front-ui'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'http://gateway-nginx.nginx-gateway.svc.cluster.local/front-ui' ]
            labels:
              app: 'front-ui'