DELETE FROM accounts;
DELETE FROM outbox_notifications;
DELETE FROM users_roles;
DELETE FROM roles;
DELETE FROM users;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE roles ALTER COLUMN id RESTART WITH 1;
ALTER TABLE accounts ALTER COLUMN id RESTART WITH 1;
ALTER TABLE outbox_notifications ALTER COLUMN id RESTART WITH 1;
